import { CredentialsContent } from "@/contracts";

export const credentialsContentAr: CredentialsContent = {
  kicker: "الشهادات والإثباتات",
  title: "الشهادات المهنية والمشاركات المجتمعية",
  description:
    "شهادات تقنية معتمدة، وبرامج هندسية، وعضويات مجتمعية ومهنية في الذكاء الاصطناعي، والشبكات، والأنظمة المضمّنة، والإدارة.",
  overviewText:
    "التعلّم العميق، ورؤية الحاسوب، والروبوتات، والأنظمة المضمّنة، وتوجيه الشبكات، وإدارة المشاريع.",
  certificationsRepoUrl: "https://github.com/a2sn2/certificates",
  certifications: [
    {
      id: "cert-cyberai-2026",
      title: "الأتمتة ووكلاء الذكاء الاصطناعي",
      issuer: "نادي CYBERAI",
      year: "2026",
      category: "AI & Data",
    },
    {
      id: "cert-yeb-research-2025",
      title: "التطوير البحثي",
      issuer: "تكتل نخبة اليمن",
      year: "2025",
      category: "Professional & Management",
    },
    {
      id: "cert-yemen-intern-2025",
      title: "أخلاقيات العمل والبيئة المهنية والعمل الجماعي",
      issuer: "منصة المتدرب اليمني",
      year: "2025",
      category: "Professional & Management",
    },
    {
      id: "cert-yeb-ai-2025",
      title: "برنامج الذكاء الاصطناعي",
      issuer: "تكتل نخبة اليمن (قطاع التقنية وتقنية المعلومات)",
      year: "2025",
      category: "AI & Data",
      status: "Ongoing",
    },
    {
      id: "cert-yeb-frontend-2025",
      title: "معسكر تطوير الواجهات الأمامية",
      issuer: "تكتل نخبة اليمن (قطاع التقنية وتقنية المعلومات)",
      year: "2025",
      category: "AI & Data",
      status: "Ongoing",
    },
    {
      id: "cert-nh-design-2025",
      title: "دبلوم التصميم الجرافيكي",
      issuer: "معاهد نيوهورايزن",
      year: "2025",
      category: "Foundation",
      status: "In Progress",
    },
    {
      id: "cert-su-dl-cv-2025",
      title: "التعلّم العميق ورؤية الحاسوب",
      issuer: "جامعة صنعاء – كلية الهندسة",
      year: "2025",
      category: "AI & Data",
    },
    {
      id: "cert-su-robotics-2025",
      title: "الروبوتات",
      issuer: "جامعة صنعاء – كلية الهندسة",
      year: "2025",
      category: "Engineering & Hardware",
    },
    {
      id: "cert-su-embedded-2025",
      title: "الأنظمة المضمّنة",
      issuer: "جامعة صنعاء – كلية الهندسة",
      year: "2025",
      category: "Engineering & Hardware",
    },
    {
      id: "cert-su-matlab-2025",
      title: "MATLAB",
      issuer: "جامعة صنعاء – كلية الهندسة",
      year: "2025",
      category: "Engineering & Hardware",
    },
    {
      id: "cert-su-netadmin-2025",
      title: "إدارة الشبكات",
      issuer: "جامعة صنعاء – كلية الهندسة",
      year: "2025",
      category: "Systems & Networks",
    },
    {
      id: "cert-su-ai-rpi-2025",
      title: "الذكاء الاصطناعي و Raspberry Pi",
      issuer: "جامعة صنعاء – كلية الهندسة",
      year: "2025",
      category: "AI & Data",
    },
    {
      id: "cert-nh-aplus-2025",
      title: "+CompTIA A",
      issuer: "معاهد نيوهورايزن",
      year: "2025",
      category: "Systems & Networks",
    },
    {
      id: "cert-ai-approach-2025",
      title: "النهج الحديث للذكاء الاصطناعي",
      issuer: "جامعة ذمار",
      year: "2025",
      category: "AI & Data",
    },
    {
      id: "cert-al-hamdi-med-prep",
      title: "التحضير الطبي والإسعافات الأولية",
      issuer: "مؤسسة الحمدي",
      year: "2024",
      category: "Foundation",
    },
    {
      id: "cert-nh-mikrotik-2024",
      title: "MikroTik Certified Network Associate (MTCNA)",
      issuer: "معاهد نيوهورايزن",
      year: "2024",
      category: "Systems & Networks",
    },
    {
      id: "cert-su-networks-2024",
      title: "أساسيات الشبكات",
      issuer: "جامعة صنعاء – كلية الهندسة",
      year: "2024",
      category: "Systems & Networks",
    },
    {
      id: "cert-su-plc-2024",
      title: "المتحكم المنطقي المبرمج PLC",
      issuer: "جامعة صنعاء – كلية الهندسة",
      year: "2024",
      category: "Engineering & Hardware",
    },
    {
      id: "cert-su-arduino-2024",
      title: "المتحكمات الدقيقة و Arduino",
      issuer: "جامعة صنعاء – كلية الهندسة",
      year: "2024",
      category: "Engineering & Hardware",
    },
    {
      id: "cert-su-solar-2024",
      title: "الطاقة الشمسية",
      issuer: "جامعة صنعاء – كلية الهندسة",
      year: "2024",
      category: "Engineering & Hardware",
    },
    {
      id: "cert-al-hamdi-marketing",
      title: "التسويق الرقمي",
      issuer: "مؤسسة الحمدي",
      year: "2024",
      category: "Foundation",
    },
    {
      id: "cert-al-hamdi-project-mgmt",
      title: "إدارة المشاريع التنموية الاحترافية (PMD Pro)",
      issuer: "مؤسسة الحمدي",
      year: "2024",
      category: "Professional & Management",
    },
    {
      id: "cert-al-hamdi-admin-program",
      title: "البرنامج الإداري (الأعمال، الموارد البشرية، خدمة العملاء)",
      issuer: "مؤسسة الحمدي",
      year: "2024",
      category: "Professional & Management",
    },
    {
      id: "cert-al-hamdi-sphere-standards",
      title: "الاستجابة الإنسانية الطارئة — SPHERE STANDARDS",
      issuer: "مؤسسة الحمدي",
      year: "2023",
      category: "Foundation",
    },
    {
      id: "cert-new-horizons-icdl",
      title: "الرخصة الدولية لقيادة الحاسوب ICDL",
      issuer: "معاهد نيوهورايزن",
      year: "2020",
      category: "Foundation",
    },
    {
      id: "cert-cst-phone-maintenance",
      title: "دبلوم صيانة الهواتف",
      issuer: "مركز العلوم والتكنولوجيا",
      year: "2019",
      category: "Engineering & Hardware",
    },
  ],
  memberships: [
    {
      id: "membership-cyberai",
      organization: "CYBERAI CLUB",
      role: "عضو في لجنتي الذكاء الاصطناعي والمشاريع.",
      description: "عضو في لجنتي الذكاء الاصطناعي والمشاريع.",
    },
    {
      id: "membership-spe",
      organization: "SOCIETY OF PETROLEUM ENGINEERS (SPE)",
      role: "عضو تقني",
      description:
        "الاستفادة من برامج SPE التقنية لتوسيع الفهم بالهندسة النفطية والعمليات.",
    },
    {
      id: "membership-al-hamdi",
      organization: "مؤسسة الحمدي للتنمية الإنسانية",
      role: "مشارك ومتطوّع",
      description: "مشارك ومتطوّع في البرامج؛ دعم الفعاليات والتعلّم النظري.",
    },
    {
      id: "membership-nastatee",
      organization: "جمعية نستطيع الخيرية",
      role: "متطوع مجتمعي",
      description: "متطوع مجتمعي يدعم مبادرات التقنية للشباب ولوجستيات الفعاليات.",
    },
    {
      id: "membership-yemen-elite",
      organization: "تكتل نخبة اليمن",
      role: "عضو تقني وإرشادي",
      description:
        "نشاط في وحدات الذكاء الاصطناعي/الروبوت والبرمجة، إرشاد الأقران ودعم لوجستيات الفعاليات.",
    },
  ],
};
