import { CredentialsContent, CredentialItem } from "@/contracts";
import { attachCredentialEvidence } from "../evidence";

const rawCertifications: CredentialItem[] = [
  {
    id: "cert-cyberai-2026",
    title: "الأتمتة ووكلاء الذكاء الاصطناعي",
    issuer: "نادي CYBERAI",
    year: "2026",
    category: "AI & Data",
  },
  {
    id: "cert-yeb-research-2025",
    title: "التطوير البحثي",
    issuer: "تكتل نخبة اليمن",
    year: "2025",
    category: "Professional & Management",
  },
  {
    id: "cert-yemen-intern-2025",
    title: "أخلاقيات العمل والبيئة المهنية والعمل الجماعي",
    issuer: "منصة المتدرب اليمني",
    year: "2025",
    category: "Professional & Management",
  },
  {
    id: "cert-yeb-ai-2025",
    title: "برنامج الذكاء الاصطناعي",
    issuer: "تكتل نخبة اليمن (قطاع التقنية وتقنية المعلومات)",
    year: "2025",
    category: "AI & Data",
    status: "Ongoing",
  },
  {
    id: "cert-yeb-frontend-2025",
    title: "معسكر تطوير الواجهات الأمامية",
    issuer: "تكتل نخبة اليمن (قطاع التقنية وتقنية المعلومات)",
    year: "2025",
    category: "AI & Data",
    status: "Ongoing",
  },
  {
    id: "cert-nh-design-2025",
    title: "دبلوم التصميم الجرافيكي",
    issuer: "معاهد نيوهورايزن",
    year: "2025",
    category: "Foundation",
    status: "In Progress",
  },
  {
    id: "cert-su-dl-cv-2025",
    title: "التعلّم العميق ورؤية الحاسوب",
    issuer: "جامعة صنعاء – كلية الهندسة",
    year: "2025",
    category: "AI & Data",
  },
  {
    id: "cert-su-robotics-2025",
    title: "الروبوتات",
    issuer: "جامعة صنعاء – كلية الهندسة",
    year: "2025",
    category: "Engineering & Hardware",
  },
  {
    id: "cert-su-embedded-2025",
    title: "الأنظمة المضمّنة",
    issuer: "جامعة صنعاء – كلية الهندسة",
    year: "2025",
    category: "Engineering & Hardware",
  },
  {
    id: "cert-su-matlab-2025",
    title: "MATLAB",
    issuer: "جامعة صنعاء – كلية الهندسة",
    year: "2025",
    category: "Engineering & Hardware",
  },
  {
    id: "cert-su-netadmin-2025",
    title: "إدارة الشبكات",
    issuer: "جامعة صنعاء – كلية الهندسة",
    year: "2025",
    category: "Systems & Networks",
  },
  {
    id: "cert-su-ai-rpi-2025",
    title: "الذكاء الاصطناعي و Raspberry Pi",
    issuer: "جامعة صنعاء – كلية الهندسة",
    year: "2025",
    category: "AI & Data",
  },
  {
    id: "cert-nh-aplus-2025",
    title: "+CompTIA A",
    issuer: "معاهد نيوهورايزن",
    year: "2025",
    category: "Systems & Networks",
  },
  {
    id: "cert-ai-approach-2025",
    title: "النهج الحديث للذكاء الاصطناعي",
    issuer: "جامعة ذمار",
    year: "2025",
    category: "AI & Data",
  },
  {
    id: "cert-alhamdi-med-2024",
    title: "التحضير الطبي والإسعافات الأولية",
    issuer: "مؤسسة الحمدي",
    year: "2024",
    category: "Foundation",
  },
  {
    id: "cert-nh-mikrotik-2024",
    title: "MikroTik Certified Network Associate (MTCNA)",
    issuer: "معاهد نيوهورايزن",
    year: "2024",
    category: "Systems & Networks",
  },
  {
    id: "cert-su-networks-2024",
    title: "أساسيات الشبكات",
    issuer: "جامعة صنعاء – كلية الهندسة",
    year: "2024",
    category: "Systems & Networks",
  },
  {
    id: "cert-su-plc-2024",
    title: "المتحكم المنطقي المبرمج PLC",
    issuer: "جامعة صنعاء – كلية الهندسة",
    year: "2024",
    category: "Engineering & Hardware",
  },
  {
    id: "cert-su-arduino-2024",
    title: "المتحكمات الدقيقة و Arduino",
    issuer: "جامعة صنعاء – كلية الهندسة",
    year: "2024",
    category: "Engineering & Hardware",
  },
  {
    id: "cert-su-solar-2024",
    title: "الطاقة الشمسية",
    issuer: "جامعة صنعاء – كلية الهندسة",
    year: "2024",
    category: "Engineering & Hardware",
  },
  {
    id: "cert-alhamdi-marketing-2024",
    title: "التسويق الرقمي",
    issuer: "مؤسسة الحمدي",
    year: "2024",
    category: "Foundation",
  },
  {
    id: "cert-alhamdi-projmgmt-2024",
    title: "إدارة المشاريع التنموية الاحترافية (PMD Pro)",
    issuer: "مؤسسة الحمدي",
    year: "2024",
    category: "Professional & Management",
  },
  {
    id: "cert-alhamdi-admin-2024",
    title: "البرنامج الإداري (الأعمال، الموارد البشرية، خدمة العملاء)",
    issuer: "مؤسسة الحمدي",
    year: "2024",
    category: "Professional & Management",
  },
  {
    id: "cert-sphere-2023",
    title: "الاستجابة الإنسانية الطارئة — SPHERE STANDARDS",
    issuer: "مؤسسة الحمدي",
    year: "2023",
    category: "Foundation",
  },
  {
    id: "cert-nh-icdl-2020",
    title: "الرخصة الدولية لقيادة الحاسوب ICDL",
    issuer: "معاهد نيوهورايزن",
    year: "2020",
    category: "Foundation",
  },
  {
    id: "cert-phone-maint-2019",
    title: "دبلوم صيانة الهواتف",
    issuer: "مركز العلوم والتكنولوجيا",
    year: "2019",
    category: "Engineering & Hardware",
  },
];

export const credentialsContentAr: CredentialsContent = {
  kicker: "الشهادات والإثباتات",
  title: "الشهادات المهنية والمشاركات المجتمعية",
  description:
    "شهادات تقنية معتمدة، وبرامج هندسية تخصصية، وعضويات مهنية ومجتمعية فاعلة تغطي الذكاء الاصطناعي، والشبكات، والأنظمة المدمجة، والإدارة.",
  overviewText:
    "التعلم العميق، الرؤية الحاسوبية، الروبوتات، الأنظمة المدمجة، توجيه الشبكات، وإدارة المشاريع.",
  certificationsRepoUrl: "https://github.com/a2sn2/certificates",
  certifications: rawCertifications.map(attachCredentialEvidence),
  memberships: [
    {
      id: "membership-cyberai",
      organization: "CYBERAI CLUB",
      role: "عضو في لجنتي الذكاء الاصطناعي والمشاريع.",
      description: "عضو في لجنتي الذكاء الاصطناعي والمشاريع.",
    },
    {
      id: "membership-spe",
      organization: "SOCIETY OF PETROLEUM ENGINEERS (SPE)",
      role: "عضو تقني",
      description:
        "الاستفادة من برامج SPE التقنية لتوسيع الفهم بالهندسة النفطية والعمليات.",
    },
    {
      id: "membership-al-hamdi",
      organization: "مؤسسة الحمدي للتنمية الإنسانية",
      role: "مشارك ومتطوّع",
      description: "مشارك ومتطوّع في البرامج؛ دعم الفعاليات والتعلّم النظري.",
    },
    {
      id: "membership-nastatee",
      organization: "جمعية نستطيع الخيرية",
      role: "متطوع مجتمعي",
      description: "متطوع مجتمعي يدعم مبادرات التقنية للشباب ولوجستيات الفعاليات.",
    },
    {
      id: "membership-yemen-elite",
      organization: "تكتل نخبة اليمن",
      role: "عضو تقني وإرشادي",
      description:
        "نشاط في وحدات الذكاء الاصطناعي/الروبوت والبرمجة، إرشاد الأقران ودعم لوجستيات الفعاليات.",
    },
  
  ],
};
