import { ProjectsContent, ProjectItem, ProjectCategory } from "@/contracts";
import { attachProjectEvidence } from "../evidence";

const rawProjectItemsAr: ProjectItem[] = [
  {
    id: "real-time-object-detection",
    slug: "real-time-object-detection",
    title: "كشف الأجسام بالزمن الحقيقي",
    tagline: "خط أنابيب حي بـ Python/PyTorch و OpenCV.",
    category: "Computer Vision & AI",
    badge: "معالجة بصرية حية",
    problem: "تتبع وكشف الأجسام المباشر واللحظي عبر تغذية كاميرا حية.",
    solution: "بناء خط أنابيب عالي الكفاءة باستخدام Python و PyTorch و OpenCV مع عرض النتائج لحظياً.",
    technologies: ["Python", "PyTorch", "OpenCV"],
    result: "معالجة حية وتتبع دقيق مع إخراج مرئي فوري.",
    featured: true,
    presentationTier: "featured",
    evidenceDepth: "rich",
  },
  {
    id: "robocam-controller",
    slug: "robocam-controller",
    title: "ROBOCAM CONTROLLER (FLUTTER + DART)",
    tagline: "تطبيق أندرويد للتحكم بروبوت مزوّد بكاميرا عبر عصا تحكّم على الشاشة.",
    category: "Systems & Robotics",
    badge: "تطبيقات الموبايل والروبوت",
    technologies: ["Flutter", "Dart", "Android Studio"],
    featured: true,
    presentationTier: "featured",
    evidenceDepth: "basic",
  },
  {
    id: "pump-station-analytics",
    slug: "pump-station-analytics",
    title: "تحليلات محطة الضخ",
    tagline: "صيانة تنبؤية لمضخات مياه الصرف الصحي.",
    category: "Systems & Robotics",
    badge: "التحكم والأتمتة الصناعية",
    technologies: ["الصيانة التنبؤية", "PLC", "تحليل البيانات"],
    featured: true,
    presentationTier: "featured",
    evidenceDepth: "basic",
  },
  {
    id: "real-time-image-classification-api",
    slug: "real-time-image-classification-api",
    title: "واجهة تصنيف صور لحظي (API)",
    tagline: "خدمة خفيفة بـ Flask تستقبل صورة وتعيد أعلى ثلاث ثقات.",
    category: "Computer Vision & AI",
    badge: "واجهة برمجة تطبيقات (API)",
    technologies: ["Python", "Flask", "API"],
    featured: false,
    presentationTier: "core",
    evidenceDepth: "basic",
  },
  {
    id: "urbanmindos",
    slug: "urbanmindos",
    title: "URBANMINDOS — نظام تشغيل المدينة الذكية",
    tagline: "إبراز التنقل الجوي الذاتي.",
    category: "Systems & Robotics",
    badge: "المدن الذكية والويب",
    technologies: ["Next.js", "TypeScript", "CSS Modules"],
    featured: false,
    presentationTier: "core",
    evidenceDepth: "basic",
  },
  {
    id: "mikrotik-hotspot-portal",
    slug: "mikrotik-hotspot-portal",
    title: "بوابة هوتسبوت MIKROTIK",
    tagline: "إعداد RouterOS مع رابطي PPPoE وبوابة Hotspot مع RADIUS. (ثنائية الوصلات Dual-WAN)",
    category: "Embedded & IoT",
    badge: "إدارة الشبكات والمصادقة",
    technologies: ["RouterOS", "MikroTik", "PPPoE", "Hotspot", "RADIUS"],
    featured: false,
    presentationTier: "core",
    evidenceDepth: "basic",
  },
  {
    id: "arduino-traffic-light",
    slug: "arduino-traffic-light",
    title: "متحكّم إشارة مرور بـ ARDUINO",
    tagline: "تقاطع باتجاهين مع حمايات آمنة وزر عبور للمشاة.",
    category: "Embedded & IoT",
    badge: "الأنظمة المضمّنة والعتاد",
    technologies: ["Arduino", "Embedded Systems", "Hardware Control"],
    featured: false,
    presentationTier: "core",
    evidenceDepth: "basic",
  },
  {
    id: "obstacle-avoidance",
    slug: "obstacle-avoidance",
    title: "تجنّب العوائق",
    tagline: "تقدير عمق أحادي الكاميرا آنياً بـ TensorFlow للكشف والتفادي.",
    category: "Computer Vision & AI",
    badge: "الذكاء الاصطناعي والتفادي",
    technologies: ["TensorFlow", "Python", "Computer Vision"],
    featured: false,
    presentationTier: "core",
    evidenceDepth: "basic",
  },
  {
    id: "ai-tic-tac-toe",
    slug: "ai-tic-tac-toe",
    title: "XO بالذكاء الاصطناعي",
    tagline: "عميل Minimax لا يُقهر بواجهة Pygame تفاعلية.",
    category: "Computer Vision & AI",
    badge: "خوارزميات الألعاب",
    technologies: ["Python", "Pygame", "Minimax"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "pacman-pygame",
    slug: "pacman-pygame",
    title: "باك-مان بـ PYGAME",
    tagline: "نسخة مع رسومات متحركة واصطدام وذكاء للأشباح وعناصر تعزيز.",
    category: "Full-Stack & Web",
    badge: "محاكاة ورسومات 2D",
    technologies: ["Python", "Pygame"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "text-summarizer",
    slug: "text-summarizer",
    title: "ملخّص نصوص",
    tagline: "تطبيق سطح مكتب للتلخيص الاستخراجي بطول قابل للضبط.",
    category: "Computer Vision & AI",
    badge: "معالجة اللغة الطبيعية",
    technologies: ["Python", "NLP", "Desktop"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "user-role-manager",
    slug: "user-role-manager",
    title: "مدير المستخدمين والأدوار",
    tagline: "إنشاء/تحديث المستخدمين، إعادة كلمات المرور، تعيين الصلاحيات — (Oracle Forms 6i + PL/SQL).",
    category: "Full-Stack & Web",
    badge: "أنظمة المؤسسات والأمان",
    technologies: ["Oracle Forms 6i", "PL/SQL", "Role Management"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "inventory-sales-manager",
    slug: "inventory-sales-manager",
    title: "مدير المخزون والمبيعات",
    tagline: "CRUD — ويب للإلكترونيات (لابتوبات/هواتف/PS5).",
    category: "Full-Stack & Web",
    badge: "إدارة المخزون والويب",
    technologies: ["CRUD", "Web Application", "Databases"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "student-evaluation-system",
    slug: "student-evaluation-system",
    title: "نظام تقييم الطالب",
    tagline: "حضور/درجات شامل مع دخول بحسب الدور (مدير/معلّم/طالب) — (C# Desktop + PHP Web).",
    category: "Full-Stack & Web",
    badge: "الأنظمة الأكاديمية",
    technologies: ["C#", "Desktop", "PHP Web"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "cafe-pos-system",
    slug: "cafe-pos-system",
    title: "نظام نقاط بيع لمقهى",
    tagline: "دخول، العناصر (CRUD)، والمبيعات/التقارير. (Java Swing + JDBC)",
    category: "Full-Stack & Web",
    badge: "نقاط البيع والمبيعات",
    technologies: ["Java Swing", "JDBC", "CRUD"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "omnifood-landing-page",
    slug: "omnifood-landing-page",
    title: "OMNIFOOD — صفحة متجاوبة",
    tagline: "صفحة واحدة مع قسم بطولي وتنقل مرسى.",
    category: "Full-Stack & Web",
    badge: "واجهة ويب متجاوبة",
    technologies: ["HTML", "CSS", "JavaScript"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
];

export const projectItemsAr: ProjectItem[] = rawProjectItemsAr.map(attachProjectEvidence);

export const projectCategoriesAr: ProjectCategory[] = [
  "All",
  "Computer Vision & AI",
  "Full-Stack & Web",
  "Systems & Robotics",
  "Embedded & IoT",
];

export const projectsContentAr: ProjectsContent = {
  kicker: "المشاريع والحلول",
  title: "المشاريع عبر الأنظمة، والرؤية، والتطبيقات",
  description:
    "أعمال هندسية منتقاة تغطي الذكاء الاصطناعي التطبيقي، والتطبيقات المتكاملة، وتوزيع الشبكات، والتحكم الصناعي.",
  categories: projectCategoriesAr,
  items: projectItemsAr,
};

export function getFeaturedProjectsAr(): ProjectItem[] {
  return projectItemsAr.filter((p) => p.presentationTier === "featured");
}

export function getProjectBySlugAr(slug: string): ProjectItem | undefined {
  return projectItemsAr.find((p) => p.slug === slug);
}

export function getAllProjectSlugsAr(): string[] {
  return projectItemsAr.map((p) => p.slug);
}
