import { CredentialsContent } from "@/contracts";

export const credentialsContent: CredentialsContent = {
  kicker: "Certifications & Proof",
  title: "Professional Credentials & Community Engagement",
  description:
    "Verified technical certifications, engineering programs, and professional community memberships across AI, networks, embedded systems, and management.",
  certificationsRepoUrl: "https://github.com/a2sn2/certificates",
  certifications: [
    {
      id: "cert-cyberai-2026",
      title: "Automation & AI Agents",
      issuer: "CYBERAI Club",
      year: "2026",
      category: "AI & Data",
      status: "Completed",
    },
    {
      id: "cert-yeb-research-2025",
      title: "Research Development Program",
      issuer: "Yemen Elite Bloc",
      year: "2025",
      category: "Professional & Management",
      status: "Completed",
    },
    {
      id: "cert-yemen-intern-2025",
      title: "Work Ethics, Professional Environment & Teamwork",
      issuer: "Yemen Intern Platform",
      year: "2025",
      category: "Professional & Management",
      status: "Completed",
    },
    {
      id: "cert-yeb-ai-2025",
      title: "Artificial Intelligence Program",
      issuer: "Yemen Elite Bloc (Tech & IT)",
      year: "2025",
      category: "AI & Data",
      status: "Ongoing",
    },
    {
      id: "cert-yeb-frontend-2025",
      title: "Front-End Development Bootcamp",
      issuer: "Yemen Elite Bloc (Tech & IT)",
      year: "2025",
      category: "AI & Data",
      status: "Ongoing",
    },
    {
      id: "cert-nh-design-2025",
      title: "Graphic Design Diploma",
      issuer: "New Horizons Institutes",
      year: "2025",
      category: "Foundation",
      status: "In Progress",
    },
    {
      id: "cert-su-dl-cv-2025",
      title: "Deep Learning & Computer Vision",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "AI & Data",
      status: "Completed",
    },
    {
      id: "cert-su-robotics-2025",
      title: "Robotics Engineering",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-su-embedded-2025",
      title: "Embedded Systems",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-su-matlab-2025",
      title: "MATLAB for Engineers",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-su-netadmin-2025",
      title: "Network Administration",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "Systems & Networks",
      status: "Completed",
    },
    {
      id: "cert-su-ai-rpi-2025",
      title: "Artificial Intelligence & Raspberry Pi",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "AI & Data",
      status: "Completed",
    },
    {
      id: "cert-nh-aplus-2025",
      title: "CompTIA A+ Hardware & IT Support",
      issuer: "New Horizons Institutes",
      year: "2025",
      category: "Systems & Networks",
      status: "Completed",
    },
    {
      id: "cert-ai-approach-2025",
      title: "Data Analysis & Machine Learning",
      issuer: "AI APPROACH CLUB",
      year: "2025",
      category: "AI & Data",
      status: "Completed",
    },
    {
      id: "cert-alhamdi-med-2024",
      title: "Medical Support Program (First Aid & Emergency)",
      issuer: "Al-Hamdi Foundation for Human Development",
      year: "2024",
      category: "Foundation",
      status: "Completed",
    },
    {
      id: "cert-nh-mikrotik-2024",
      title: "MikroTik RouterOS Fundamentals",
      issuer: "New Horizons Institutes",
      year: "2024",
      category: "Systems & Networks",
      status: "Completed",
    },
    {
      id: "cert-su-networks-2024",
      title: "Computer Networks & Architecture",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2024",
      category: "Systems & Networks",
      status: "Completed",
    },
    {
      id: "cert-su-plc-2024",
      title: "Programmable Logic Controllers (PLC)",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2024",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-su-arduino-2024",
      title: "Arduino Microcontrollers & Automation",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2024",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-su-solar-2024",
      title: "Solar Energy & Inverter Systems",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2024",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-alhamdi-marketing-2024",
      title: "Advanced Digital Marketing",
      issuer: "Al-Hamdi Foundation for Human Development",
      year: "2024",
      category: "Foundation",
      status: "Completed",
    },
    {
      id: "cert-alhamdi-projmgmt-2024",
      title: "Small Project Management",
      issuer: "Al-Hamdi Foundation for Human Development",
      year: "2024",
      category: "Professional & Management",
      status: "Completed",
    },
    {
      id: "cert-alhamdi-admin-2024",
      title: "Administrative Systems (Business, HR, Customer Service)",
      issuer: "Al-Hamdi Foundation for Human Development",
      year: "2024",
      category: "Professional & Management",
      status: "Completed",
    },
    {
      id: "cert-sphere-2023",
      title: "Emergency Humanitarian Response — SPHERE Standards",
      issuer: "Al-Hamdi Foundation for Human Development",
      year: "2023",
      category: "Foundation",
      status: "Completed",
    },
    {
      id: "cert-nh-icdl-2020",
      title: "ICDL (International Computer Driving Licence)",
      issuer: "New Horizons Institutes",
      year: "2020",
      category: "Foundation",
      status: "Completed",
    },
    {
      id: "cert-phone-maint-2019",
      title: "Mobile Hardware Maintenance Diploma",
      issuer: "Science & Technology Center",
      year: "2019",
      category: "Engineering & Hardware",
      status: "Completed",
    },
  ],
  memberships: [
    {
      id: "membership-cyberai",
      organization: "CYBERAI CLUB",
      role: "Member of Artificial Intelligence & Projects Committees",
      description:
        "Participated in applied AI discussions, technical workshops, and exploratory machine learning projects.",
    },
    {
      id: "membership-spe",
      organization: "Society of Petroleum Engineers (SPE)",
      role: "Active Member",
      description:
        "Utilized SPE technical resources and seminars to broaden understanding of energy infrastructure and industrial control applications.",
    },
    {
      id: "membership-yeb",
      organization: "Yemen Elite Bloc",
      role: "Member of AI, Robotics & Programming Units",
      description:
        "Collaborated with engineering peers on robotics projects, software bootcamps, and technical mentoring initiatives.",
    },
    {
      id: "membership-alhamdi",
      organization: "Al-Hamdi Foundation for Human Development",
      role: "Program Participant & Community Volunteer",
      description:
        "Contributed to organizational logistics, peer learning initiatives, and community service workshops.",
    },
    {
      id: "membership-nastatee",
      organization: "Nastatee Charity Association",
      role: "Community Volunteer",
      description:
        "Supported youth education and technology literacy events through logistical and technical coordination.",
    },
  ],
};
