import { CredentialsContent } from "@/contracts";

export const credentialsContent: CredentialsContent = {
  kicker: "Certifications & Proof",
  title: "Professional Credentials & Community Engagement",
  description:
    "Verified technical certifications, engineering programs, and professional community memberships across AI, networks, embedded systems, and management.",
  overviewText:
    "Deep learning, computer vision, robotics, embedded systems, network routing, and project management.",
  certificationsRepoUrl: "https://github.com/a2sn2/certificates",
  certifications: [
    {
      id: "cert-cyberai-2026",
      title: "Automation & AI Agents",
      issuer: "CYBERAI Club",
      year: "2026",
      category: "AI & Data",
      status: "Completed",
    },
    {
      id: "cert-yeb-research-2025",
      title: "Research Development",
      issuer: "Yemen Elite Bloc",
      year: "2025",
      category: "Professional & Management",
      status: "Completed",
    },
    {
      id: "cert-yemen-intern-2025",
      title: "Work Ethics, Professional Environment & Teamwork",
      issuer: "Yemen Intern Platform",
      year: "2025",
      category: "Professional & Management",
      status: "Completed",
    },
    {
      id: "cert-yeb-ai-2025",
      title: "Artificial Intelligence Program (Ongoing)",
      issuer: "Yemen Elite Bloc (Technology & IT Sector)",
      year: "2025",
      category: "AI & Data",
      status: "Ongoing",
    },
    {
      id: "cert-yeb-frontend-2025",
      title: "Front-End Development Bootcamp (Ongoing)",
      issuer: "Yemen Elite Bloc (Technology & IT Sector)",
      year: "2025",
      category: "AI & Data",
      status: "Ongoing",
    },
    {
      id: "cert-nh-design-2025",
      title: "Graphic Design Diploma (In Progress)",
      issuer: "New Horizons Institutes",
      year: "2025",
      category: "Foundation",
      status: "In Progress",
    },
    {
      id: "cert-su-dl-cv-2025",
      title: "Deep Learning & Computer Vision",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "AI & Data",
      status: "Completed",
    },
    {
      id: "cert-su-robotics-2025",
      title: "Robotics",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-su-embedded-2025",
      title: "Embedded Systems",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-su-matlab-2025",
      title: "MATLAB",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-su-netadmin-2025",
      title: "Network Administration",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "Systems & Networks",
      status: "Completed",
    },
    {
      id: "cert-su-ai-rpi-2025",
      title: "Artificial Intelligence & Raspberry Pi",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2025",
      category: "AI & Data",
      status: "Completed",
    },
    {
      id: "cert-nh-aplus-2025",
      title: "CompTIA A+",
      issuer: "New Horizons Institutes",
      year: "2025",
      category: "Systems & Networks",
      status: "Completed",
    },
    {
      id: "cert-ai-approach-2025",
      title: "Data Analysis & Machine Learning",
      issuer: "AI APPROACH CLUB",
      year: "2025",
      category: "AI & Data",
      status: "Completed",
    },
    {
      id: "cert-alhamdi-med-2024",
      title: "Medical Program (First Aid, Injection Types, Vital Signs)",
      issuer: "Al-Hamdi Foundation for Human Development",
      year: "2024",
      category: "Foundation",
      status: "Completed",
    },
    {
      id: "cert-nh-mikrotik-2024",
      title: "MikroTik Fundamentals",
      issuer: "New Horizons Institutes",
      year: "2024",
      category: "Systems & Networks",
      status: "Completed",
    },
    {
      id: "cert-su-networks-2024",
      title: "Networks",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2024",
      category: "Systems & Networks",
      status: "Completed",
    },
    {
      id: "cert-su-plc-2024",
      title: "Programmable Logic Controllers (PLC)",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2024",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-su-arduino-2024",
      title: "Arduino",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2024",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-su-solar-2024",
      title: "Solar Energy",
      issuer: "Sana'a University – Faculty of Engineering",
      year: "2024",
      category: "Engineering & Hardware",
      status: "Completed",
    },
    {
      id: "cert-alhamdi-marketing-2024",
      title: "Advanced Digital Marketing",
      issuer: "Al-Hamdi Foundation for Human Development",
      year: "2024",
      category: "Foundation",
      status: "Completed",
    },
    {
      id: "cert-alhamdi-projmgmt-2024",
      title: "Small Project Management",
      issuer: "Al-Hamdi Foundation for Human Development",
      year: "2024",
      category: "Professional & Management",
      status: "Completed",
    },
    {
      id: "cert-alhamdi-admin-2024",
      title: "Administrative Program (Business, Human Resources, Customer Service)",
      issuer: "Al-Hamdi Foundation for Human Development",
      year: "2024",
      category: "Professional & Management",
      status: "Completed",
    },
    {
      id: "cert-sphere-2023",
      title: "Emergency Humanitarian Response — SPHERE Standards",
      issuer: "Al-Hamdi Foundation for Human Development",
      year: "2023",
      category: "Foundation",
      status: "Completed",
    },
    {
      id: "cert-nh-icdl-2020",
      title: "ICDL (International Computer Driving Licence)",
      issuer: "New Horizons Institutes",
      year: "2020",
      category: "Foundation",
      status: "Completed",
    },
    {
      id: "cert-phone-maint-2019",
      title: "Mobile Phone Maintenance Diploma",
      issuer: "Science & Technology Center",
      year: "2019",
      category: "Engineering & Hardware",
      status: "Completed",
    },
  ],
  memberships: [
    {
      id: "membership-cyberai",
      organization: "CYBERAI CLUB",
      role: "Member of the Artificial Intelligence and Projects Committees",
      description:
        "Member of the Artificial Intelligence and Projects Committees.",
    },
    {
      id: "membership-spe",
      organization: "Society of Petroleum Engineers (SPE)",
      role: "Technical Program Participant",
      description:
        "Used SPE technical programs to broaden understanding of petroleum engineering and operations.",
    },
    {
      id: "membership-alhamdi",
      organization: "Al-Hamdi Foundation for Human Development",
      role: "Program Participant & Volunteer",
      description:
        "Program participant and volunteer; supported events and peer learning.",
    },
    {
      id: "membership-nastatee",
      organization: "Nastatee Charity Association",
      role: "Community Volunteer",
      description:
        "Community volunteer supporting youth technology initiatives and event logistics.",
    },
    {
      id: "membership-yeb",
      organization: "Yemen Elite Bloc",
      role: "Active Member",
      description:
        "Active in AI/robotics and programming units; peer mentoring and event logistics support.",
    },
  ],
};
