import { ProjectsContent, ProjectItem, ProjectCategory } from "@/contracts";
import { attachProjectEvidence } from "../evidence";

const rawProjectItemsDe: ProjectItem[] = [
  {
    id: "real-time-object-detection",
    slug: "real-time-object-detection",
    title: "Echtzeit-Objekterkennung",
    tagline: "Live-Pipeline mit Python/PyTorch und OpenCV.",
    category: "Computer Vision & AI",
    badge: "Computer-Vision-Pipeline",
    problem: "Echtzeit-Objekterkennung auf einem Live-Videostream.",
    solution: "Hochperformante Pipeline mit Python, PyTorch und OpenCV zur Live-Kamerabildverarbeitung.",
    technologies: ["Python", "PyTorch", "OpenCV"],
    result: "Live-Pipeline mit Echtzeitvisualisierung der Ergebnisse.",
    featured: true,
    presentationTier: "featured",
    evidenceDepth: "rich",
  },
  {
    id: "robocam-controller",
    slug: "robocam-controller",
    title: "ROBOCAM CONTROLLER (FLUTTER + DART)",
    tagline: "Android-App zur Steuerung eines kameragestützten Roboters über einen Bildschirm-Joystick.",
    category: "Systems & Robotics",
    badge: "Mobile & Robotik",
    technologies: ["Flutter", "Dart", "Android"],
    featured: true,
    presentationTier: "featured",
    evidenceDepth: "basic",
  },
  {
    id: "pump-station-analytics",
    slug: "pump-station-analytics",
    title: "Pumpstation-Analytik",
    tagline: "Vorausschauende Wartung für Abwasserpumpen.",
    category: "Systems & Robotics",
    badge: "Industrielle Automatisierung",
    technologies: ["Vorausschauende Wartung"],
    featured: true,
    presentationTier: "featured",
    evidenceDepth: "basic",
  },
  {
    id: "real-time-image-classification-api",
    slug: "real-time-image-classification-api",
    title: "Echtzeit-Bildklassifizierungs-API",
    tagline: "Leichter Flask-Dienst, der ein Bild entgegennimmt und die drei wahrscheinlichsten Klassen zurückgibt.",
    category: "Computer Vision & AI",
    badge: "Microservice-API",
    technologies: ["Python", "Flask", "API"],
    featured: false,
    presentationTier: "core",
    evidenceDepth: "basic",
  },
  {
    id: "urbanmindos",
    slug: "urbanmindos",
    title: "URBANMINDOS — Smart-City-Betriebssystem",
    tagline: "Präsentiert autonome urbane Luftmobilität.",
    category: "Systems & Robotics",
    badge: "Konzeptdesign",
    technologies: ["Konzeptdesign", "Urbane Luftmobilität"],
    featured: false,
    presentationTier: "core",
    evidenceDepth: "basic",
  },
  {
    id: "mikrotik-hotspot-portal",
    slug: "mikrotik-hotspot-portal",
    title: "MIKROTIK-Hotspot-Portal",
    tagline: "Dual-WAN-RouterOS-Setup mit PPPoE-Leitungen, Hotspot-Portal und RADIUS.",
    category: "Embedded & IoT",
    badge: "Netzwerktechnik",
    technologies: ["MikroTik RouterOS", "Dual-WAN", "PPPoE", "Hotspot Portal", "RADIUS"],
    featured: false,
    presentationTier: "core",
    evidenceDepth: "basic",
  },
  {
    id: "arduino-traffic-light",
    slug: "arduino-traffic-light",
    title: "ARDUINO-Ampelsteuerung",
    tagline: "Zweirichtungs-Kreuzung mit Sicherheitslogik und Fußgänger-Taster.",
    category: "Embedded & IoT",
    badge: "Eingebettete Systeme",
    technologies: ["Arduino"],
    featured: false,
    presentationTier: "core",
    evidenceDepth: "basic",
  },
  {
    id: "obstacle-avoidance",
    slug: "obstacle-avoidance",
    title: "Hindernisvermeidung",
    tagline: "Echtzeit-Monokulartiefenschätzung mit TensorFlow zur Erkennung und Ausweichsteuerung.",
    category: "Computer Vision & AI",
    badge: "Robotik & KI",
    technologies: ["TensorFlow", "Tiefenschätzung"],
    featured: false,
    presentationTier: "core",
    evidenceDepth: "basic",
  },
  {
    id: "ai-tic-tac-toe",
    slug: "ai-tic-tac-toe",
    title: "KI-Tic-Tac-Toe",
    tagline: "Unschlagbare Minimax-KI mit interaktiver Pygame-Oberfläche.",
    category: "Computer Vision & AI",
    badge: "Spiele-KI",
    technologies: ["Python", "Pygame", "Minimax-KI"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "pacman-pygame",
    slug: "pacman-pygame",
    title: "Pac-Man mit PYGAME",
    tagline: "Version mit Animationen, Kollisionserkennung, Geist-KI und Power-ups.",
    category: "Full-Stack & Web",
    badge: "Spieleentwicklung",
    technologies: ["Python", "Pygame", "Kollisionserkennung"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "text-summarizer",
    slug: "text-summarizer",
    title: "Textzusammenfasser",
    tagline: "Desktop-Anwendung zur extraktiven Zusammenfassung mit einstellbarer Ausgabelänge.",
    category: "Computer Vision & AI",
    badge: "NLP-Werkzeug",
    technologies: ["Desktop-Anwendung", "Extraktive Zusammenfassung"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "user-role-manager",
    slug: "user-role-manager",
    title: "Benutzer- & Rollenverwaltung",
    tagline: "Benutzer erstellen/aktualisieren, Passwörter zurücksetzen und Berechtigungen vergeben (Oracle Forms 6i + PL/SQL).",
    category: "Full-Stack & Web",
    badge: "Unternehmenssysteme",
    technologies: ["Oracle Forms 6i", "PL/SQL"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "inventory-sales-manager",
    slug: "inventory-sales-manager",
    title: "Inventar- & Vertriebsmanager",
    tagline: "CRUD-Webanwendung für Elektronik (Laptops/Smartphones/PS5).",
    category: "Full-Stack & Web",
    badge: "Webanwendung",
    technologies: ["Webanwendung", "CRUD"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "student-evaluation-system",
    slug: "student-evaluation-system",
    title: "Schülerbewertungssystem",
    tagline: "Anwesenheits- und Notensystem mit rollenbasiertem Zugriff (Admin/Lehrkraft/Schüler) — C# Desktop + PHP Web.",
    category: "Full-Stack & Web",
    badge: "Mehrschichtige Anwendung",
    technologies: ["C#", "Desktop", "PHP", "Web"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "cafe-pos-system",
    slug: "cafe-pos-system",
    title: "Café-POS-System",
    tagline: "Login, CRUD für Artikel, Verkäufe und Berichte (Java Swing + JDBC).",
    category: "Full-Stack & Web",
    badge: "Desktop-Anwendung",
    technologies: ["Java Swing", "JDBC"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
  {
    id: "omnifood-landing-page",
    slug: "omnifood-landing-page",
    title: "OMNIFOOD — Responsive Landingpage",
    tagline: "Einseitiges Layout mit Hero-Bereich und Ankernavigation.",
    category: "Full-Stack & Web",
    badge: "Webdesign",
    technologies: ["Responsive Web"],
    featured: false,
    presentationTier: "archive",
    evidenceDepth: "basic",
  },
];

export const projectItemsDe: ProjectItem[] = rawProjectItemsDe.map(attachProjectEvidence);

export const projectCategoriesDe: ProjectCategory[] = [
  "All",
  "Computer Vision & AI",
  "Full-Stack & Web",
  "Systems & Robotics",
  "Embedded & IoT",
];

export const projectsContentDe: ProjectsContent = {
  kicker: "Projekte & Arbeiten",
  title: "Entwicklungsprojekte in Systemen, Vision & Web",
  description:
    "Ausgewählte technische Arbeiten aus angewandter KI, Anwendungsentwicklung, Netzwerkinfrastruktur und industrieller Steuerung.",
  categories: projectCategoriesDe,
  items: projectItemsDe,
};

export function getFeaturedProjectsDe(): ProjectItem[] {
  return projectItemsDe.filter((p) => p.presentationTier === "featured");
}

export function getProjectBySlugDe(slug: string): ProjectItem | undefined {
  return projectItemsDe.find((p) => p.slug === slug);
}

export function getAllProjectSlugsDe(): string[] {
  return projectItemsDe.map((p) => p.slug);
}
